# -*- coding: utf-8 -*-
"""HolaMundo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mAxC9oEHv_h_Q1hzF_c190sTNFwOxBOF
"""

print("Hola Mundo")